import { ArrowRight, MapPin, Phone, ShieldCheck } from "lucide-react";
import { Link } from "wouter";
import { ADDRESS, CallButton, PHONE, SEO, locationSlug, locations } from "../App";
import { servicePages } from "../data/services";

function DirectoryServiceCard({ service }: { service: typeof servicePages[number] }) {
  const Icon = service.icon;
  return <Link href={`/${service.slug}`} className="service-card directory-card"><div className="service-icon"><Icon size={22} /></div><h3>{service.title}</h3><p>{service.short}</p><span className="text-link">{service.title} <ArrowRight size={15} /></span></Link>;
}

function DirectoryAreaCard({ location }: { location: string }) {
  return <Link href={`/plumber-${locationSlug(location)}`} className="area-directory-card"><div className="area-card-icon"><MapPin size={22} /></div><div><span className="eyebrow">Service area</span><h3>Plumber in {location}</h3><p>Local plumbing support for homes and businesses in {location.replace(", FL", "")}.</p><span className="text-link">Plumber in {location} <ArrowRight size={15} /></span></div></Link>;
}

export function ServicesDirectory() {
  return <><SEO title="Plumbing Services in Weston, FL | Weston FL Plumber" description={`Explore complete plumbing services in Weston, FL including repairs, drains, leaks, water heaters, toilets, and more. Call ${PHONE}.`} schema={{"@context":"https://schema.org","@type":"CollectionPage","name":"Plumbing Services in Weston, FL","about":"Plumbing services","url":"https://www.westonflplumber.com/services"}} /><section className="directory-hero"><div className="container directory-hero-inner"><div><Link href="/" className="crumb">Home / Services</Link><span className="eyebrow light">Professional plumbing support</span><h1>Plumbing services in <i>Weston, FL</i>.</h1><p>Find the right plumbing service for your home or business. Each service page includes useful context, what to expect, and a direct way to call.</p><CallButton>Call Now</CallButton></div><div className="directory-hero-note"><ShieldCheck size={25} /><strong>Start with the symptom.</strong><span>Tell us what changed, where it is happening, and how long it has been going on.</span></div></div></section><section className="section"><div className="container"><div className="section-heading"><div><span className="eyebrow">Weston service directory</span><h2>Complete plumbing support, organized clearly.</h2></div><p>Browse the full list of Weston-focused services below. For a nearby community, visit our service area directory.</p></div><div className="service-grid directory-grid">{servicePages.map(service => <DirectoryServiceCard key={service.slug} service={service} />)}</div></div></section><section className="soft-section section"><div className="container directory-cta"><div><span className="eyebrow">Need help choosing?</span><h2>Speak with a plumber about what you are seeing.</h2><p>We can help you understand the most useful next step before you call the team.</p></div><a href="tel:+17542838022" className="btn-primary"><Phone size={17} /> {PHONE}</a></div></section></>;
}

export function ServiceAreaDirectory() {
  return <><SEO title="Service Areas | Weston FL Plumber" description={`Weston FL Plumber serves Weston and nearby South Florida communities including Miramar, Pembroke Pines, Cooper City, Southwest Ranches, and Davie. Call ${PHONE}.`} schema={{"@context":"https://schema.org","@type":"CollectionPage","name":"Weston FL Plumber Service Areas","url":"https://www.westonflplumber.com/service-area"}} /><section className="directory-hero area-directory-hero"><div className="container directory-hero-inner"><div><Link href="/" className="crumb">Home / Service area</Link><span className="eyebrow light">Weston first · nearby communities welcome</span><h1>Our plumbing service <i>area</i>.</h1><p>Weston is our main location, with service support extending into nearby South Florida communities. Choose a location below for local information and plumbing help.</p><CallButton>Call Now</CallButton></div><div className="directory-hero-note"><MapPin size={25} /><strong>Main location</strong><span>{ADDRESS}</span><a href="https://maps.app.goo.gl/qDUEhqRhmaQgg3tJ7" target="_blank" rel="noreferrer" className="text-link light-link">View on Google Maps <ArrowRight size={15} /></a></div></div></section><section className="section"><div className="container"><div className="section-heading"><div><span className="eyebrow">Nearby South Florida communities</span><h2>Find a plumber near you.</h2></div><p>Each location page is written for the community it serves and connects you to the Weston FL Plumber team.</p></div><div className="area-directory-grid"><Link href="/plumber-weston-fl" className="area-directory-card featured-area"><div className="area-card-icon"><MapPin size={22} /></div><div><span className="eyebrow">Main location</span><h3>Plumber in Weston, FL</h3><p>Full-service plumbing support from our primary Weston location.</p><span className="text-link">Plumber in Weston, FL <ArrowRight size={15} /></span></div></Link>{locations.map(location => <DirectoryAreaCard key={location} location={location} />)}</div></div></section><section className="soft-section section"><div className="container directory-cta"><div><span className="eyebrow">Ready when you need us</span><h2>Have a plumbing question?</h2><p>Call {PHONE} and tell us where you are located and what is happening.</p></div><a href="tel:+17542838022" className="btn-primary"><Phone size={17} /> {PHONE}</a></div></section></>;
}
