import { Link } from "wouter";
import { ArrowRight, Bath, Check, ChevronDown, Clock3, Droplets, Flame, Gauge, House, MapPin, Phone, Pipette, ShieldCheck, Sparkles, Star, Waves, Wrench } from "lucide-react";
import { useState } from "react";
import { ADDRESS, MAP_LINK, PHONE, PHONE_HREF, SEO, servicePages } from "../App";

const areas = ["Weston", "Miramar", "Pembroke Pines", "Cooper City", "Southwest Ranches", "Davie", "Plantation", "Sunrise", "Pembroke Park", "Hialeah"];
const problems = ["Dripping or leaking fixtures", "Slow or backed-up drains", "No hot water", "Running or clogged toilets", "Low water pressure", "Unexplained moisture or odors", "Garbage disposal issues", "Pipe and supply line leaks"];

function HomeFaq({ q, a }: { q: string; a: string }) { const [open, setOpen] = useState(false); return <div className={open ? "faq open" : "faq"}><button onClick={() => setOpen(!open)}><span>{q}</span><ChevronDown size={18} /></button>{open && <p>{a}</p>}</div>; }
function ServiceCard({ service }: { service: typeof servicePages[number] }) { const Icon = service.icon; return <Link href={`/${service.slug}`} className="service-card"><div className="service-icon"><Icon size={22} /></div><h3>{service.title}</h3><p>{service.short}</p><span className="text-link">{service.title} <ArrowRight size={15} /></span></Link>; }

export default function Home() { return <>
  <SEO title="Weston FL Plumber | Professional Plumbing in Weston, Florida" description={`Clear answers and careful plumbing service for Weston, FL homes and businesses. Call ${PHONE}.`} schema={{"@context":"https://schema.org","@type":"Plumber","name":"Weston FL Plumber","url":"https://www.westonflplumber.com/","telephone":PHONE,"address":{"@type":"PostalAddress","streetAddress":"2645 Executive Park Drive","addressLocality":"Weston","addressRegion":"FL","postalCode":"33331","addressCountry":"US"},"areaServed":areas.map(area => ({"@type":"City","name":area}))}} />
  <section className="hero"><div className="hero-bg"></div><div className="container hero-inner"><div className="hero-copy"><span className="eyebrow light">Weston’s local plumbing team</span><h1>Plumber in <i>Weston, FL</i> for the moments that matter.</h1><p>Clear answers, careful workmanship, and practical plumbing support for homes and businesses in Weston and nearby South Florida communities.</p><div className="hero-actions"><a className="btn-primary" href={PHONE_HREF}><Phone size={17} /> Call Now</a><a className="btn-ghost-light" href="#services">View all plumbing services <ArrowRight size={17} /></a></div><div className="hero-note"><ShieldCheck size={17} /><span>Local service · Straightforward communication · Respect for your property</span></div></div><div className="hero-stat"><span>Need help now?</span><strong>{PHONE}</strong><small>Call to speak with a plumber.</small></div></div><div className="hero-bottom"><div className="container hero-bottom-inner"><span><Clock3 size={16} /> Call for service guidance</span><span><MapPin size={16} /> Serving Weston, FL first</span><span><Wrench size={16} /> Residential & commercial plumbing</span></div></div></section>
  <section className="intro section"><div className="container intro-grid"><div className="intro-image"><img src="/manus-storage/weston-plumber-service_fcc91054.jpg" alt="Professional plumber inspecting a water heater in a South Florida home" /><div className="image-badge"><strong>Weston, Florida</strong><span>Plumbing done with care</span></div></div><div className="intro-copy"><span className="eyebrow">About Weston FL Plumber</span><h2>A better plumbing experience starts with listening.</h2><p>Plumbing problems are disruptive enough without vague answers or unnecessary complexity. Weston FL Plumber is built around a simple idea: understand what is happening, explain what we find, and help you choose a practical next step.</p><p>From everyday fixture repairs to leaks, drains, water heaters, and urgent plumbing concerns, we bring a calm, professional approach to the homes and businesses we serve in Weston.</p><div className="mini-points"><div><Check size={16} /><span>Clear communication</span></div><div><Check size={16} /><span>Careful in-home service</span></div><div><Check size={16} /><span>Practical recommendations</span></div></div><Link href="/plumber-weston-fl" className="text-link">Learn about our plumbing service <ArrowRight size={16} /></Link></div></div></section>
  <section id="services" className="soft-section section"><div className="container"><div className="section-heading"><div><span className="eyebrow">Complete plumbing services</span><h2>Help for the systems your day depends on.</h2></div><p>Explore focused plumbing services for Weston homes and businesses. Every service page includes useful context, what to expect, and a direct way to call.</p></div><div className="service-grid">{servicePages.map(service => <ServiceCard key={service.slug} service={service} />)}</div><div className="center-cta"><Link href="/plumber-weston-fl" className="btn-secondary">Start with Weston plumbing service <ArrowRight size={17} /></Link></div></div></section>
  <section className="split-feature section"><div className="container split-feature-grid"><div className="split-copy"><span className="eyebrow">When plumbing cannot wait</span><h2>Small signs can point to a bigger problem.</h2><p>Water where it should not be, a drain that keeps slowing down, or a water heater that changes behavior can all be useful signals. Getting clear on the cause early may help protect your home and your schedule.</p><div className="feature-list"><div><span className="feature-number">01</span><p><strong>Start with the symptoms.</strong> Tell us what changed and when you noticed it.</p></div><div><span className="feature-number">02</span><p><strong>Focus the inspection.</strong> We look at the fixture, line, or system connected to the issue.</p></div><div><span className="feature-number">03</span><p><strong>Choose the next step.</strong> You get useful information before moving forward.</p></div></div><a href={PHONE_HREF} className="text-link">Call {PHONE} <ArrowRight size={16} /></a></div><div className="split-image"><img src="/manus-storage/weston-plumber-drain_1c18ecd9.jpg" alt="Plumber inspecting a kitchen drain with a camera" /><div className="image-caption"><span className="caption-dot"></span> Drain & sewer support in Weston</div></div></div></section>
  <section id="why-us" className="why-section section"><div className="container"><div className="section-heading centered"><span className="eyebrow">Why choose us</span><h2>Professional service without the runaround.</h2><p>When something in your home is not working, you deserve a team that makes the next step feel more manageable.</p></div><div className="why-grid"><div className="why-card"><div className="why-icon"><ShieldCheck /></div><h3>Respect for your space</h3><p>We treat floors, cabinetry, fixtures, and finished rooms like they matter—because they do.</p></div><div className="why-card"><div className="why-icon"><Gauge /></div><h3>Focused diagnosis</h3><p>We pay attention to the pattern behind the symptom so you can make a more informed decision.</p></div><div className="why-card"><div className="why-icon"><Sparkles /></div><h3>Clean, clear communication</h3><p>Know what we are looking at, what we found, and what the useful next step could be.</p></div></div></div></section>
  <section id="service-area" className="area-section section"><div className="container area-grid"><div><span className="eyebrow">Service area</span><h2>Weston first. Nearby communities welcome.</h2><p>Weston is our main location, with service support extending into nearby South Florida communities. Explore a location page for a closer look at how we can help.</p><div className="area-pills">{areas.map((area, i) => <Link key={area} href={i === 0 ? "/plumber-weston-fl" : `/plumber-${area.toLowerCase().replaceAll(" ", "-")}-fl`}>{area}, FL</Link>)}</div><a href={MAP_LINK} target="_blank" rel="noreferrer" className="text-link">View Weston location on Google Maps <ArrowRight size={16} /></a></div><div className="map-card"><iframe title="Weston FL Plumber location map" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1835252.349245451!2d-82.44260179080565!3d26.05065508657955!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x88d90b486768c50f%3A0xa7fa6d410079f71a!2sWeston%20Fl%20Plumber!5e0!3m2!1sen!2sin!4v1790576466757!5m2!1sen!2sin" loading="lazy"></iframe><div className="map-label"><MapPin size={16} /><span>{ADDRESS}</span></div></div></div></section>
  <section className="reviews-section section"><div className="container reviews-grid"><div><span className="eyebrow">Customer feedback</span><h2>Trust is earned one call at a time.</h2><p>We do not publish unverified testimonials. As verified customer feedback becomes available, this space will reflect the experience of real Weston FL Plumber customers.</p><a href={PHONE_HREF} className="text-link">Be the first to speak with our team <ArrowRight size={16} /></a></div><div className="review-placeholder"><div className="review-stars">{[1,2,3,4,5].map(n => <Star key={n} size={18} />)}</div><h3>Real service. Real conversations.</h3><p>Call now for a clear, professional conversation about your plumbing needs.</p><a href={PHONE_HREF} className="btn-secondary"><Phone size={16} /> {PHONE}</a></div></div></section>
  <section className="faq-section section"><div className="container faq-layout"><div><span className="eyebrow">Frequently asked questions</span><h2>Helpful answers before you call.</h2><p>Not sure what kind of plumbing service you need? Start with the symptom. We can help you identify the most useful next step.</p><Link href="/plumber-weston-fl" className="text-link">See Weston plumbing services <ArrowRight size={16} /></Link></div><div className="faq-list"><HomeFaq q="What areas do you serve?" a="Weston is our main location. We also serve nearby communities including Miramar, Pembroke Pines, Cooper City, Southwest Ranches, and Davie." /><HomeFaq q="What should I do if I have an active leak?" a="If it is safe, shut off the nearest fixture valve or your main water supply and move items away from the water. Call promptly for help with the next step." /><HomeFaq q="Can you help with a slow drain?" a="Yes. A slow drain can come from buildup, a local blockage, or a deeper restriction. Tell us which fixtures are affected and whether the problem keeps returning." /><HomeFaq q="What if I smell gas?" a="Leave the area immediately and contact your gas utility or emergency services. Do not use switches, flames, or appliances in the area. For non-emergency plumbing questions, call once the situation is safe." /></div></div></section>
  <section id="contact" className="home-contact"><div className="container home-contact-inner"><div><span className="eyebrow light">Talk with the team</span><h2>Need a plumber in Weston?</h2><p>Call now to discuss your plumbing concern and request service.</p></div><a href={PHONE_HREF} className="btn-primary"><Phone size={18} /> {PHONE}</a></div></section>
</>; }
